### ISSUE TITLE
regenerate geojson for RES=6

### ISSUE THREAD

**Issue by MathewBiddle** [MathewBiddle/globe#19]
https://h3geo.org/docs/core-library/restable/#average-area-in-km2

https://github.com/MathewBiddle/globe/blob/b649e5b458715781c392aa70e0cb3ef579571939/use_parquet_file_for_globe.Rmd#L196

Record how much time it takes.

**Comment by MathewBiddle** [comment]
Couldn't generate at H3 resolution 6 (see [resolutions](https://h3geo.org/docs/core-library/restable/)) for the entire snapshot. Memory usage at 24.23GB.

![image](https://github.com/user-attachments/assets/ddefe392-edc3-4a28-96c2-ce5e94833ffa)


```
Error: memory exhausted (limit reached?)
```

Code:
```R
> ptm <- proc.time()
> # grid resolution
> # 3 = 15 mins
> # 6 = 
> RES <- 6
> 
> # map defaults
> column <- "es"
> label <- "ES(50)"
> trans <- "identity"
> crs <- "+proj=eqc +lat_ts=0 +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs"
> limits <- c(0,50)
> 
> 
> # make grid
> grid_dec <- res_changes(occ, RES)
Error: memory exhausted (limit reached?)
```

So, now we have to figure out what the capacity is for running this locally, or explore other more performant solutions. Like `h3o` cited at https://github.com/marinebon/obisindicators/issues/31#issuecomment-2284887007.

**Comment by MathewBiddle** [comment]
My system info:
```
Processor	Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz   2.11 GHz
Installed RAM	32.0 GB (31.8 GB usable)
System type	64-bit operating system, x64-based processor
```

**Comment by MathewBiddle** [comment]
probably subsetting to us marine waters.

@mimidiorio do you have a polygon for the region of interest? That will help with compute resources.

**Comment by mimidiorio** [comment]
@MathewBiddle 
H3 grids (H2-H6) clipped to US waters (and coasts) [are here](https://drive.google.com/file/d/1XHompy8Hj2nbDscfxJZFJ5JUGM3nWzY7/view?usp=drive_link)

USwaters shapefile is [here](https://drive.google.com/file/d/1aFNZA8cZAosTJ9R9KXTlsbss67NC6Xym/view?usp=sharing)

**Comment by MathewBiddle** [comment]
Tried to run the H3 grid at resolution 6 for 1 year (1970-1971) between 0 < Lat < 74.7, 160 < Lon < -40 (an extremely rough approximation of US waters bounding box). 

```R
dec_beg <- 1970

occ_dec <- 
  occ %>%
  filter(between(decimalLatitude,0.00,74.7)) %>%
  filter(between(decimalLongitude,-180.0,-40.0) | between(decimalLongitude,160.0,180.0)) %>%
  filter(
      date_year >= dec_beg,
      date_year <= dec_beg+1)
```
Even with this significant reduction in data, I ran into `Error: memory exhausted (limit reached?)`.

It used used 24.37GB memory before it bailed. 

## What do we do now?
At H3 resolution 6 we are creating hexagons with the average area of **36 km^2** (according to the [spec](https://h3geo.org/docs/core-library/restable/#average-area-in-km2)). I think resolution 4 (1,770 km^2) or 5 (252 km^2) would be more feasible and could significantly reduce the processing needed to generate the data.

I'll try to run the grid for resolution 5 and see if that succeeds with this massive reduction in data.

**Comment by mimidiorio** [comment]
Phooey.  If you can get H4 to run, let's check that out.  Have asked for NODD space/access.  Not really sure what exactly we need, but seeing what might be available to us.  Any specs or requirements I can relay to the NODD team would help.

**Comment by MathewBiddle** [comment]
I was able to run a one-year US coastal waters obisindicators for resolutions 3, 4, and 5. Here's what that looks like:
![image](https://github.com/user-attachments/assets/ae1dc148-79a9-4033-847d-844cd7e4ad49)

Details on runtime and memory:
resolution | appprox area (km^2) | time to run (sec) | Output size (MB) | Memory used (GB)
-----------|-----------------------|------------------|------------------|--------------------
3 | 12393 |  82.65  | 1.0 | 3.51
4 |  1770 | 561.95 | 2.7 | 2.25
5 |   252 | 6351.06 | 5.8 | 12.94
6 |    36 | Crashes with "Error: memory exhausted (limit reached?)" |  | 24.37GB memory used before crash

**Comment by MathewBiddle** [comment]
@mimidiorio you can find the tests for the different resolutions at:

resolution | link
-----------|-----
3 | https://github.com/MathewBiddle/globe/blob/main/data/indicators_1970_1971_res3.geojson
4 | https://github.com/MathewBiddle/globe/blob/main/data/indicators_1970_1971_res4.geojson
5 | https://github.com/MathewBiddle/globe/blob/main/data/indicators_1970_1971_res5.geojson

**Comment by mimidiorio** [comment]
Looks like the res5 file covers a lot more than coastal waters.  Can you clip to US waters before you run? Looking into the NODD as an option too.    
![h5_19701971](https://github.com/user-attachments/assets/29fe146c-e85c-4987-867b-f5ea82a3e86c)

**Comment by MathewBiddle** [comment]
I have been testing with subsetting the OBIS snapshot down to the polygon @mimidiorio provided (.shp added to the PR above, let me know if this is **not** okay). Even with that significant reduction in data (35million records down to 39k) it still takes a long time to run the H3 gridding process at resolution 6. 

One positive is that I am no longer running into memory limitations. But, I am still only testing with one year of data (1970-1971). 

The next step is to dig into the grid generating function to see why that is taking so long. Is it generating a global grid and then trying to compute for all grids? We only need it to generate for the regions of interest. We might be able to optimize `obisindicators`.

**Comment by MathewBiddle** [comment]
I think I'm getting a clearer picture. `obisindicators` first builds a global H3 grid at the resolution you request.

https://github.com/marinebon/obisindicators/blob/9b1ef2fed175f47b21f65280cfa0f903666502ed/R/h3.R#L35-L38

Building a grid at resolution 6 takes a long time! So, how can we optimize that process to build a grid only for data we have?

**Comment by MathewBiddle** [comment]
xref: https://github.com/marinebon/obisindicators/issues/45

**Comment by MathewBiddle** [comment]
@mimidiorio I was able to make res=6 indicator from 1970-1971. 

See the geosjon at:
https://github.com/MathewBiddle/globe/blob/main/data/indicators_1970_1971_res6.geojson

**Comment by MathewBiddle** [comment]
here is my memory usage for res6 US Waters for one year:
![image](https://github.com/user-attachments/assets/1e65ddc7-f4c1-4419-8ce4-668808feb742)

```
> gc()
            used   (Mb) gc trigger   (Mb)  max used    (Mb)
Ncells  24865732 1328.0  177079315 9457.1 345858035 18470.9
Vcells 290764946 2218.4  814872988 6217.0 766190872  5845.6
```
