### ISSUE TITLE
change the icons

### ISSUE THREAD

**Issue by 7yl4r** [MathewBiddle/globe#5]
either use all the same icon, use numbers, or find icons that represent each decasde

**Comment by 7yl4r** [comment]
My thematic icon proposal:

text | icon text | icon img
-----|-----------|-----------
all  | TbSum   | ![image](https://user-images.githubusercontent.com/1051390/191556062-32c44650-606d-4062-abb6-ecddab06be1b.png)
60s  | FaPeace | ![image](https://user-images.githubusercontent.com/1051390/191554040-26b9b8b1-7ff6-4e83-9052-f2d906612bd5.png)
70s  | FaGasPump | ![image](https://user-images.githubusercontent.com/1051390/191554787-ce5b4aa9-eeb7-41e1-a768-8377d833da50.png)
80s  | GiBrokenWall | ![image](https://user-images.githubusercontent.com/1051390/191554928-62716812-6835-48cf-afab-5225a1c80028.png)
90s  | SiWindows95 | ![image](https://user-images.githubusercontent.com/1051390/191555287-25aa08dc-6eff-4f6d-92c8-92f81e156272.png)
00s  | BsGraphDown | ![image](https://user-images.githubusercontent.com/1051390/191555398-e6091801-529c-4f8d-9c89-b003fed9773f.png)
10s  | MdPhoneIphone | ![image](https://user-images.githubusercontent.com/1051390/191555694-c0d500aa-0c81-4dfa-83ca-634d89fd2900.png)
20s  | RiVirusLine | ![image](https://user-images.githubusercontent.com/1051390/191555934-ae301cd8-dbcb-48a0-aa27-3fd30c7c2a9c.png)

**Comment by MathewBiddle** [comment]
Just stuck in the years as text. Done in
* https://github.com/MathewBiddle/globe/commit/402f0b7a15dd2b005bdbd6820e41f468f8870ed6

**Comment by MathewBiddle** [comment]
@7yl4r I do like those icons though!!
