### ISSUE TITLE
colorbar / legend

### ISSUE THREAD

**Issue by 7yl4r** [MathewBiddle/globe#7]
It would be nice to have a colorbar or legend in the UI, but for now maybe we can put a colorbar and references in the readme

**Comment by MathewBiddle** [comment]
Added in commits:
* https://github.com/MathewBiddle/globe/commit/1f50dbb85e5a6ee6da47deeda38b53c660f714e9
* https://github.com/MathewBiddle/globe/commit/5fc6f66f6166489c96bec5e5e8f8ae6150f1e3e3
* https://github.com/MathewBiddle/globe/commit/0fb40291ee7555befc06eb4d6bd193eff6f21c80
* https://github.com/MathewBiddle/globe/commit/d11b902c71f466bc91d982c8cecd110f64eb8e93
